version: "3"

services:
  libcoverage:
    image: libcoverage/test-php74:latest
    build:
      context: ../..
      dockerfile: docker/test-php74/Dockerfile
    working_dir: /DATA
    volumes:
      - ../../:/DATA
      - ./composer-test-php74.lock:/DATA/composer.lock
      - libcoverage-data-for-tests74:/DATA/tests/data_for_tests
      - libcoverage-vendor74:/DATA/vendor
      - libcoverage-composer-cache74:/tmp/composer
      - ./test_reports:/DATA/test_reports
      - ./test_coveragedumps:/DATA/test_coveragedumps
    environment:
      - COMPOSER_HOME=/tmp/composer
      - XDEBUG_MODE=coverage
    command:
      - sh
      - -c
      - |
        cd /DATA &&
        [ -f /DATA/composer.lock ] || (echo composer.lock_missing; exit 1)
        if [ ! -d /DATA/vendor ] || [ ! -f /DATA/vendor/autoload.php ]; then
          composer install --no-interaction --prefer-dist --no-scripts
        fi
        composer exec phpunit
        tail -f /dev/null

volumes:
  libcoverage-vendor74:
  libcoverage-composer-cache74:
  libcoverage-data-for-tests74: