version: "3"

services:
  libcoverage:
    image: libcoverage/test-php74:latest
    build:
      context: ../..
      dockerfile: docker/test-php74/Dockerfile
    working_dir: /DATA
    volumes:
      - ../../:/DATA
      - libcoverage-data-for-tests74:/DATA/tests/data_for_tests
      - libcoverage-vendor74:/DATA/vendor
      - libcoverage-composer-cache74:/tmp/composer
      - ./test_reports:/DATA/test_reports
      - ./test_coveragedumps:/DATA/test_coveragedumps
    environment:
      - COMPOSER_HOME=/tmp/composer
      - XDEBUG_MODE=coverage
    command:
      - sh
      - -c
      - |
        cd /DATA &&
        rm -f /DATA/composer.lock &&
        composer update
        composer exec phpunit

volumes:
  libcoverage-vendor74:
  libcoverage-composer-cache74:
  libcoverage-data-for-tests74: